const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
require('dotenv').config();
const { Client } = require('pg');

const ALLOWED_TRACKING_TABLES = new Set(['schema_migrations', 'schema_seeders']);

function getConnectionString() {
  return process.env.SUPABASE_DB_URL || process.env.DATABASE_URL;
}

function getSqlFiles(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory)
    .filter((filename) => filename.toLowerCase().endsWith('.sql'))
    .sort((a, b) => a.localeCompare(b));
}

function computeChecksum(sqlText) {
  return crypto.createHash('sha256').update(sqlText).digest('hex');
}

function assertValidTrackingTable(tableName) {
  if (!ALLOWED_TRACKING_TABLES.has(tableName)) {
    throw new Error(`Tracking table "${tableName}" is not allowed`);
  }
}

async function ensureTrackingTable(client, tableName) {
  assertValidTrackingTable(tableName);
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.${tableName} (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      filename TEXT NOT NULL UNIQUE,
      checksum TEXT NOT NULL,
      executed_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
    );
  `);
}

async function runSqlDirectory({ directory, tableName, label }) {
  const connectionString = getConnectionString();
  if (!connectionString) {
    throw new Error('Missing SUPABASE_DB_URL (or DATABASE_URL) in .env');
  }

  const files = getSqlFiles(directory);
  if (files.length === 0) {
    console.log(`No ${label} files found in ${directory}`);
    return;
  }

  const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false }
  });

  await client.connect();
  await ensureTrackingTable(client, tableName);

  try {
    for (const filename of files) {
      const absolutePath = path.join(directory, filename);
      const sqlText = fs.readFileSync(absolutePath, 'utf8');
      const checksum = computeChecksum(sqlText);

      const existing = await client.query(
        `SELECT checksum FROM public.${tableName} WHERE filename = $1 LIMIT 1`,
        [filename]
      );

      if (existing.rows.length > 0) {
        const executedChecksum = existing.rows[0].checksum;
        if (executedChecksum !== checksum) {
          throw new Error(
            `${label} file "${filename}" has changed after execution. Create a new file instead of editing existing ${label}.`
          );
        }
        console.log(`Skipping ${label}: ${filename} (already executed)`);
        continue;
      }

      console.log(`Running ${label}: ${filename}`);
      await client.query('BEGIN');
      try {
        await client.query(sqlText);
        await client.query(
          `INSERT INTO public.${tableName} (filename, checksum) VALUES ($1, $2)`,
          [filename, checksum]
        );
        await client.query('COMMIT');
      } catch (error) {
        await client.query('ROLLBACK');
        throw error;
      }
    }
  } finally {
    await client.end();
  }
}

module.exports = {
  runSqlDirectory
};
